// Compiles assets/catalog/sprites/*.json into
// lib/engine/generators/sprite_data.g.dart so sprites are available
// synchronously everywhere, including background isolates.
//
//   dart run tool/build_sprites.dart
import 'dart:convert';
import 'dart:io';

import 'package:glyph/engine/generators/sprite.dart';

void main() {
  final dir = Directory('assets/catalog/sprites');
  final files = dir.listSync().whereType<File>().where((f) => f.path.endsWith('.json')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final ids = <String>{};
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/build_sprites.dart from assets/catalog/sprites/*.json.')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln('const builtInSpritePacks = <String>[');
  var total = 0;
  for (final f in files) {
    final src = f.readAsStringSync();
    final sprites = Sprite.parsePack(src); // validates
    for (final s in sprites) {
      if (!ids.add(s.id)) throw StateError('duplicate sprite id ${s.id} in ${f.path}');
    }
    total += sprites.length;
    final min = jsonEncode(jsonDecode(src));
    if (min.contains("'''")) throw StateError('${f.path} contains triple quotes');
    out.writeln("  r'''$min''',");
    stdout.writeln('${f.uri.pathSegments.last}: ${sprites.length} sprites');
  }
  out.writeln('];');
  File('lib/engine/generators/sprite_data.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('total: $total sprites');
}
