// Draws Glyph's app icon: a lowercase "g" in amber LED dots on the dark
// panel colour. Flat, one colour, no glow, so it stays crisp at launcher size.
// (The animated arcade "g" lives on as the device's boot intro.)
//
//   dart run tool/make_icon.dart
//
// Writes the SVG source (assets/brand/glyph_icon.svg), the adaptive icon's
// vector foreground, legacy PNGs for Android 7, and PNG previews.
import 'dart:io';

import 'package:image/image.dart' as img;

const _bg = 0xFF0B0A09;
const _amber = 0xFFFFB547;

/// The "g" on a 5×7 grid of LEDs.
const _g = [
  '.###.',
  '#...#',
  '#...#',
  '.####',
  '....#',
  '#...#',
  '.###.',
];

/// Lit dot centres on a [box]-unit canvas, [pitch] units apart, centred.
Iterable<(double, double)> _dots(double box, double pitch) sync* {
  for (var r = 0; r < _g.length; r++) {
    for (var c = 0; c < _g[r].length; c++) {
      if (_g[r][c] == '#') yield (box / 2 + (c - 2) * pitch, box / 2 + (r - 3) * pitch);
    }
  }
}

// Proportions on the 108-unit adaptive canvas. Launchers show the middle
// 72 units, so the "g" (about 41 tall) reads like the full-bleed preview,
// well inside the 66-unit safe zone.
const _box = 108.0, _pitch = 6.0, _radius = 2.4;

String _f(double v) => v.toStringAsFixed(2).replaceFirst(RegExp(r'\.?0+$'), '');

String svg({bool background = true}) {
  final b = StringBuffer('<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72">\n');
  if (background) b.writeln('  <rect x="18" y="18" width="72" height="72" fill="#0B0A09"/>');
  b.writeln('  <g fill="#FFB547">');
  for (final (x, y) in _dots(_box, _pitch)) {
    b.writeln('    <circle cx="${_f(x)}" cy="${_f(y)}" r="$_radius"/>');
  }
  b.writeln('  </g>\n</svg>');
  return b.toString();
}

/// Android vector drawable for the adaptive foreground (and monochrome).
String vectorDrawable() {
  final paths = [
    for (final (x, y) in _dots(_box, _pitch))
      'M${_f(x - _radius)},${_f(y)}a$_radius,$_radius 0 1,0 ${_f(2 * _radius)},0a$_radius,$_radius 0 1,0 ${_f(-2 * _radius)},0z',
  ].join();
  return '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_icon.dart; edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFB547"
        android:pathData="$paths" />
</vector>
''';
}

img.ColorRgba8 _c(int argb) => img.ColorRgba8((argb >> 16) & 0xFF, (argb >> 8) & 0xFF, argb & 0xFF, 0xFF);

/// Full-bleed raster: the visible 72-unit square scaled to [size] px.
img.Image render(int size, {bool rounded = false}) {
  // Supersample so the dots' edges come out smooth.
  const ss = 4;
  final big = size * ss;
  final im = img.Image(width: big, height: big, numChannels: 4);
  final k = big / 72;
  if (rounded) {
    img.fillRect(im, x1: 0, y1: 0, x2: big - 1, y2: big - 1, color: _c(_bg), radius: (big * 0.06).round());
  } else {
    img.fill(im, color: _c(_bg));
  }
  for (final (x, y) in _dots(_box, _pitch)) {
    img.fillCircle(im,
        x: ((x - 18) * k).round(), y: ((y - 18) * k).round(), radius: (_radius * k).round(), color: _c(_amber), antialias: true);
  }
  return img.copyResize(im, width: size, height: size, interpolation: img.Interpolation.average);
}

void main(List<String> args) {
  const res = 'android/app/src/main/res';
  const legacy = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192};
  for (final MapEntry(:key, :value) in legacy.entries) {
    File('$res/mipmap-$key/ic_launcher.png').writeAsBytesSync(img.encodePng(render(value)));
    // The old raster foregrounds are replaced by the vector drawable.
    final old = File('$res/mipmap-$key/ic_launcher_foreground.png');
    if (old.existsSync()) old.deleteSync();
  }
  File('$res/drawable/ic_launcher_foreground.xml').writeAsStringSync(vectorDrawable());
  Directory('$res/mipmap-anydpi-v26').createSync(recursive: true);
  File('$res/mipmap-anydpi-v26/ic_launcher.xml').writeAsStringSync('''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
''');
  File('$res/values/ic_launcher_background.xml').writeAsStringSync('''<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">#0B0A09</color>
</resources>
''');
  Directory('assets/brand').createSync(recursive: true);
  File('assets/brand/glyph_icon.svg').writeAsStringSync(svg());
  File('assets/brand/glyph_icon_1024.png').writeAsBytesSync(img.encodePng(render(1024, rounded: true)));
  File('docs/media/icon.png').writeAsBytesSync(img.encodePng(render(256, rounded: true)));
  stdout.writeln('icons written; source: assets/brand/glyph_icon.svg');
}
