// Captured from a real device: WLED 16.0.1 on ESP32 (16x16 matrix), 2026-10-02.
const infoEsp32V16 = r'''{"ver":"16.0.1","vid":2606300,"cn":"Niji","release":"ESP32","repo":"wled/WLED","deviceId":"8afb88510397142c7f483bddcf7bd2818e31cc59ac","leds":{"count":256,"pwr":1000,"fps":42,"maxpwr":1000,"maxseg":32,"bootps":102,"matrix":{"w":16,"h":16},"seglc":[1],"lc":1,"rgbw":false,"wv":0,"cct":0},"str":false,"name":"WLED","udpport":21324,"simplifiedui":false,"live":false,"liveseg":-1,"lm":"","lip":"","ws":1,"fxcount":220,"palcount":72,"cpalcount":0,"umpalcount":0,"cpalmax":129,"maps":[{"id":0}],"wifi":{"bssid":"92:87:4C:85:AD:17","rssi":-90,"signal":20,"channel":11,"ap":false},"fs":{"u":98,"t":983,"pmt":0},"ndc":0,"arch":"esp32","core":"4.4.8.240628","clock":240,"flash":4,"lwip":0,"bootloaderSHA256":"cb0d5304552dc2c817a30ce40a9524e266dee844fef2803dc7e49f69b6aadfba","freeheap":92748,"uptime":603,"time":"2026-10-2, 18:49:00","um":[32],"u":{"AudioReactive":["<button class=\"btn btn-xs\" onclick=\"requestJson({AudioReactive:{enabled:true}});\"><i class=\"icons off\">&#xe08f;</i></button>"]},"opt":79,"brand":"WLED","product":"FOSS","mac":"48e729a39308","ip":"192.168.29.6"}''';

/// /json/eff from the same device ("Image" is index 53).
const effectsEsp32V16 = <String>[
  'Solid',
  'Blink',
  'Breathe',
  'Wipe',
  'Wipe Random',
  'Random Colors',
  'Sweep',
  'Dynamic',
  'Colorloop',
  'Rainbow',
  'Scan',
  'Scan Dual',
  'Fade',
  'Theater',
  'Theater Rainbow',
  'Running',
  'Saw',
  'Twinkle',
  'Dissolve',
  'Dissolve Rnd',
  'Sparkle',
  'Sparkle Dark',
  'Sparkle+',
  'Strobe',
  'Strobe Rainbow',
  'Strobe Mega',
  'Blink Rainbow',
  'Android',
  'Chase',
  'Chase Random',
  'Chase Rainbow',
  'Chase Flash',
  'Chase Flash Rnd',
  'Rainbow Runner',
  'Colorful',
  'Traffic Light',
  'Sweep Random',
  'Chase 2',
  'Aurora',
  'Stream',
  'Scanner',
  'Lighthouse',
  'Fireworks',
  'Rain',
  'Tetrix',
  'Fire Flicker',
  'Gradient',
  'Loading',
  'Rolling Balls',
  'Fairy',
  'Two Dots',
  'Fairytwinkle',
  'Running Dual',
  'Image',
  'Chase 3',
  'Tri Wipe',
  'Tri Fade',
  'Lightning',
  'ICU',
  'Multi Comet',
  'Scanner Dual',
  'Stream 2',
  'Oscillate',
  'Pride 2015',
  'Juggle',
  'Palette',
  'Fire 2012',
  'Colorwaves',
  'Bpm',
  'Fill Noise',
  'Noise 1',
  'Noise 2',
  'Noise 3',
  'Noise 4',
  'Colortwinkles',
  'Lake',
  'Meteor',
  'Copy Segment',
  'Railway',
  'Ripple',
  'Twinklefox',
  'Twinklecat',
  'Halloween Eyes',
  'Solid Pattern',
  'Solid Pattern Tri',
  'Spots',
  'Spots Fade',
  'Glitter',
  'Candle',
  'Fireworks Starburst',
  'Fireworks 1D',
  'Bouncing Balls',
  'Sinelon',
  'Sinelon Dual',
  'Sinelon Rainbow',
  'Popcorn',
  'Drip',
  'Plasma',
  'Percent',
  'Ripple Rainbow',
  'Heartbeat',
  'Pacifica',
  'Candle Multi',
  'Solid Glitter',
  'Sunrise',
  'Phased',
  'Twinkleup',
  'Noise Pal',
  'Sine',
  'Phased Noise',
  'Flow',
  'Chunchun',
  'Dancing Shadows',
  'Washing Machine',
  'Rotozoomer',
  'Blends',
  'TV Simulator',
  'Dynamic Smooth',
  'Spaceships',
  'Crazy Bees',
  'Ghost Rider',
  'Blobs',
  'Scrolling Text',
  'Drift Rose',
  'Distortion Waves',
  'Soap',
  'Octopus',
  'Waving Cell',
  'Pixels',
  'Pixelwave',
  'Juggles',
  'Matripix',
  'Gravimeter',
  'Plasmoid',
  'Puddles',
  'Midnoise',
  'Noisemeter',
  'Freqwave',
  'Freqmatrix',
  'GEQ',
  'Waterfall',
  'Freqpixels',
  'RSVD',
  'Noisefire',
  'Puddlepeak',
  'Noisemove',
  'Noise2D',
  'Perlin Move',
  'Ripple Peak',
  'Firenoise',
  'Squared Swirl',
  'PacMan',
  'DNA',
  'Matrix',
  'Metaballs',
  'Freqmap',
  'Gravcenter',
  'Gravcentric',
  'Gravfreq',
  'DJ Light',
  'Funky Plank',
  'Shimmer',
  'Pulser',
  'Blurz',
  'Drift',
  'Waverly',
  'Sun Radiation',
  'Colored Bursts',
  'Julia',
  'RSVD',
  'RSVD',
  'RSVD',
  'Game Of Life',
  'Tartan',
  'Polar Lights',
  'Swirl',
  'Lissajous',
  'Frizzles',
  'Plasma Ball',
  'Flow Stripe',
  'Hiphotic',
  'Sindots',
  'DNA Spiral',
  'Black Hole',
  'Wavesins',
  'Rocktaves',
  'Akemi',
  'PS Volcano',
  'PS Fire',
  'PS Fireworks',
  'PS Vortex',
  'PS Fuzzy Noise',
  'PS Ballpit',
  'PS Box',
  'PS Attractor',
  'PS Impact',
  'PS Waterfall',
  'PS Spray',
  'PS GEQ 2D',
  'PS GEQ Nova',
  'PS Ghost Rider',
  'PS Blobs',
  'PS DripDrop',
  'PS Pinball',
  'PS Dancing Shadows',
  'PS Fireworks 1D',
  'PS Sparkler',
  'PS Hourglass',
  'PS Spray 1D',
  'PS 1D Balance',
  'PS Chase',
  'PS Starburst',
  'PS GEQ 1D',
  'PS Fire 1D',
  'PS Sonic Stream',
  'PS Sonic Boom',
  'PS Springy',
  'PS Galaxy',
  'Color Clouds',
  'Slow Transition',
];

/// ESP8266-style info as older firmware reports it: no matrix, fs or flash.
const infoEsp8266V014 = r'''{"ver":"0.14.4","vid":2405180,"leds":{"count":30,"pwr":0,"fps":42,"maxpwr":850,"maxseg":16,"seglc":[1],"lc":1,"rgbw":false,"wv":0,"cct":0},"str":false,"name":"Desk strip","udpport":21324,"live":false,"liveseg":-1,"lm":"","lip":"","ws":0,"fxcount":187,"palcount":71,"cpalcount":0,"maps":[{"id":0}],"wifi":{"bssid":"00:11:22:33:44:55","rssi":-62,"signal":76,"channel":6},"arch":"esp8266","core":"2_7_4_7","lwip":1,"freeheap":21304,"uptime":1234,"opt":127,"brand":"WLED","product":"FOSS","mac":"aabbccddeeff","ip":"192.168.1.50"}''';
